


let projectsData = [
    {
        title:"Animation Library",
        image:"animlib.jpg",
        techniques:"Javascript",
        info:"For easy animation directly in Html code.",
        link:"https://github.com/xPMoss/anim.lib",
        show: true,
    },
    {
        title:"Link Database",
        image:"ld.jpg",
        techniques:"Javascript, html, css",
        info:"Coding with Html, Css & Javascript. Testing some filtering code",
        link:"https://github.com/xPMoss/link-database-client",
        show: true,
    },
    {
        title:"The Movie App",
        image:"tmdb.jpg",
        techniques:"Javascript, html, css",
        info:"Coding with Html, Css & Javascript. A movie website",
        link:"https://xpmoss.github.io/tma/",
        show: true,
    },
    {
        title:"The Movie Service",
        image:"tms.jpg",
        techniques:"Angular, TypeScript, html, css",
        info:"Coding with Angular. A movie website",
        link:"https://the-movie-service.web.app/",
        show: true,
    },
    {
        title:"Tree view",
        image:"tw.jpg",
        techniques:"Javascript, html, css",
        info:"Coding with canvas. A W.I.P tree view with javascript",
        link:"https://xpmoss.github.io/treeview/",
        show: true,
    },
    {
        title:"Snake",
        image:"snake.jpg",
        techniques:"C#",
        info:"Snake Game made with C#",
        link:"https://github.com/xPMoss/snake",
        show: true,
    },
    {
        title:"3D Engine",
        image:"3d_engine.jpg",
        techniques:"Javascript, html, css",
        info:"Testing coding with canvas. A 'fake' 3D box with javascript",
        link:"https://xpmoss.github.io/threedcube/",
        show: true,
    },
    {
        title:"Turbosquid",
        image:"ts.jpg",
        techniques:"3D-graphics, modelling, texturing, rendering",
        info:"My turbosquid page",
        link:"https://www.turbosquid.com/Search/Artists/wemg?referral=wemg",
        show: true,

    },
    {
        title:"JavaScript Mario",
        image:"js-mario.jpg",
        techniques:"Javascript, html, css",
        info:"A mario game made with JavaScript and canvas, very W.I.P",
        link:"https://github.com/xPMoss/js-mario",
        show: true,

    },
    {
        title:"Calender",
        image:"calender.jpg",
        techniques:"Angular, TypeScript, html, css",
        info:"A calender made in Angular. Keep track of worked hours",
        link:"https://github.com/xPMoss/calender-client",
        show: true,

    }




]


let animationData = 
[
    { 
        title: "showreel",
        headline: "Showreel",
	    productioncompany: "Misc",
	    client: "Misc",
	    techniques: "3D-graphics, Animation, Rendering, Compositing",
		thumbnail: "images/showreel_wide.png",
	    video: "https://player.vimeo.com/video/316567932",
		image: "images/showreel_wide.png",
		link: "https://vimeo.com/316567932",
	    info: "NULL",
	    content: "video",
        status: "online",
        page: "showreel",
		software: "NULL",
		tags: "NULL"

    }, 
    { 
        title: "stripe",
        headline: "Stripe Add",
	    productioncompany: "Stripe",
	    client: "Stripe",
	    techniques: "3D-graphics, Rendering, Compositing",
		thumbnail: "images/content/small/stripe.jpg",
	    video: "NULL",
		image: "images/content/small/stripe.jpg",
		link: "NULL",
	    info: "NULL",
	    content: "image",
        status: "online",
        page: "portfolio",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "elkjop",
	    headline: "Elkjøp Commercial",
	    productioncompany: "Stripe",
	    client: "Elkjøp",
	    techniques: "3D-graphics, Animation, Rendering",
		thumbnail: "images/content/small/elkjop.jpg",
	    video: "https://player.vimeo.com/video/8697469",
        image: "images/content/elkjop.jpg",
		link: "https://vimeo.com/8697469",
	    info: "NULL",
	    content: "video",
	    status: "online",
        page: "portfolio",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "lunda",
	    headline: "Lundabrädan",
	    productioncompany:"",
	    client: "The association Lundabrädan",
	    techniques: "3D-graphics, Rendering, Compositing",
		thumbnail: "images/content/small/lunda.jpg",
	    video: "NULL",
        image: "images/content/lunda.jpg",
		link: "NULL",
	    info: "NULL",
	    content: "image",
	    status: "online",
        page: "portfolio",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title:"coalition",
	    headline: "Coalition of the Willing",
	    productioncompany: "Sehsucht",
	    client: "",
	    techniques: "",
		thumbnail: "images/content/small/coalition.jpg",
	    video: "",
        image: "images/content/coalition.jpg",
		link: "NULL",
	    info: "NULL",
	    content: "video",
	    status: "online",
        page: "portfolio",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "o2",
	    headline: "O2 Commercial",
	    productioncompany: "Sehsucht",
	    client: "O2",
	    techniques: "Animation Previz/Tests",
		thumbnail: "images/content/small/o2.jpg",
	    video: "https://player.vimeo.com/video/16307205",
        image: "images/content/o2.jpg",
		link: "https://vimeo.com/16307205",
	    info: "NULL",
	    content: "video",
	    status: "online",
        page: "portfolio",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "ceros",
	    headline: "Ceros 200",
	    productioncompany: "Logical Arts",
	    client: "SAAB Group",
	    techniques: "3D/2D-graphics, Animation, Particle effects, Rendering, Compositing",
		thumbnail: "images/content/small/ceros.jpg",
	    video: "https://www.youtube.com/embed/YGVP2LtRp64",
        image: "images/content/ceros.jpg",
		link: "https://www.youtube.com/watch?v=YGVP2LtRp64",
	    info: "NULL",
	    content: "video",
	    status: "online",
        page: "portfolio",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "bms",
	    headline: "9L BMS",
	    productioncompany: "Logical Arts",
	    client: "SAAB Group",
	    techniques: "3D/2D-graphics, Animation, Tracking, Rendering, Compositing",
		thumbnail: "images/content/small/bms.jpg",
	    video: "https://www.youtube.com/embed/y279obKTuKE",
        image: "images/content/bms.jpg",
		link: "https://www.youtube.com/watch?v=y279obKTuKE",
	    info: "9Land Battle Management System",
	    content: "video",
	    status: "online",
        page: "portfolio",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "rapid",
	    headline: "Rapid 3D Mapping",
	    productioncompany: "Logical Arts",
	    client: "SAAB Group",
	    techniques: "3D/2D-graphics, Animation, Particle effects",
		thumbnail: "images/content/small/rapid.jpg",
	    video: "https://player.vimeo.com/video/336417003",
        image: "images/content/rapid.jpg",
		link: "https://vimeo.com/336417003",
	    info: "NULL",
	    content: "video",
	    status: "online",
        page: "portfolio",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "tacticall",
	    headline: "Tacticall",
	    productioncompany: "Logical Arts",
	    client: "SAAB Group",
	    techniques: "3D/2D-graphics, Animation, Tracking, Rendering, Compositing",
		thumbnail: "images/content/small/tacticall.jpg",
	    video: "https://player.vimeo.com/video/336416342",
        image: "images/content/tacticall.jpg",
		link: "https://vimeo.com/336416342",
	    info: "NULL",
	    content: "video",
	    status: "online",
        page: "portfolio",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "idisplay_darwin",
	    headline: "Absolut Darwin",
	    productioncompany: "Mediabolaget",
	    client: "The Absolut Company",
	    techniques: "3D/2D-graphics, Animation, Rendering, Compositing",
		thumbnail: "images/content/small/idisplay_darwin.jpg",
	    video: "https://player.vimeo.com/video/336421256",
        image: "images/content/idisplay_darwin.jpg",
		link: "https://vimeo.com/336421256",
	    info: "Absolut Darwin - Store Display",
	    content: "video",
	    status: "online",
        page: "portfolio",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "idisplay_sleeve",
	    headline: "Absolut Sleeve",
	    productioncompany: "Mediabolaget",
	    client: "The Absolut Company",
	    techniques: "3D/2D-graphics, Animation, Rendering, Compositing",
		thumbnail: "images/content/small/idisplay_sleeve.jpg",
	    video: "https://player.vimeo.com/video/336421214",
        image: "images/content/idisplay_sleeve.jpg",
		link: "https://vimeo.com/336421214",
	    info: "Store Display",
	    content: "video",
	    status: "online",
        page: "portfolio",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "idisplay_moy",
	    headline: "Absolut Mid of Year 2017",
	    productioncompany: "Mediabolaget",
	    client: "The Absolut Company",
	    techniques: "3D/2D-graphics, Animation, Rendering, Compositing",
		thumbnail: "images/content/small/idisplay_moy.jpg",
	    video: "https://player.vimeo.com/video/336421302",
        image: "images/content/idisplay_moy.jpg",
		link: "https://vimeo.com/336421302",
	    info: "Store Display",
	    content: "video",
	    status: "online",
        page: "portfolio",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "idisplay_rainbow",
	    headline: "Absolut Rainbow",
	    productioncompany: "Mediabolaget",
	    client: "The Absolut Company",
	    techniques: "3D/2D-graphics, Animation, Rendering, Compositing",
		thumbnail: "images/content/small/idisplay_rainbow.jpg",
	    video: "https://player.vimeo.com/video/336421342",
        image: "images/content/idisplay_rainbow.jpg",
		link: "https://vimeo.com/336421342",
	    info: "Store Display",
	    content: "video",
	    status: "online",
        page: "portfolio",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "absolut_new_design",
	    headline: "Absolut.",
	    productioncompany: "Mediabolaget",
	    client: "The Absolut Company",
	    techniques: "3D/2D-graphics, Animation, Rendering, Compositing",
		thumbnail: "images/content/small/absolut_new_design.jpg",
	    video: "https://player.vimeo.com/video/336418541",
        image: "images/content/absolut_new_design.jpg",
		link: "NULL",
	    info: "NULL",
	    content: "video",
	    status: "online",
        page: "portfolio",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "slussen_tos",
	    headline: "Trafik och stadsliv",
	    productioncompany: "Mediabolaget",
	    client: "Stockholms Stad",
	    techniques: "3D/2D-graphics, Animation, Rendering, Compositing",
		thumbnail: "images/content/small/slussen_tos.jpg",
	    video: "https://player.vimeo.com/video/49220363",
        image: "images/content/slussen_tos.jpg",
		link: "NULL",
	    info: "NULL",
	    content: "video",
	    status: "online",
        page: "portfolio",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "slussen_tub",
	    headline: "Trafik under byggtiden",
	    productioncompany: "Mediabolaget",
	    client: "Stockholms Stad",
	    techniques: "3D/2D-graphics, Animation, Rendering, Compositing",
		thumbnail: "images/content/small/slussen_tub.jpg",
	    video: "https://www.youtube.com/embed/F7pqymN6fvQ",
        image: "images/content/slussen_tub.jpg",
		link: "NULL",
	    info: "NULL",
	    content: "video",
	    status: "online",
        page: "portfolio",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "slussen_land",
	    headline: "Tekniska utmaningar på land",
	    productioncompany: "Mediabolaget",
	    client: "Stockholms Stad",
	    techniques: "2D-animation",
		thumbnail: "images/content/small/slussen_land.jpg",
	    video: "https://www.youtube.com/embed/CZ_Ib4xgCqw",
        image: "images/content/slussen_land.jpg",
		link: "NULL",
	    info: "NULL",
	    content: "video",
	    status: "online",
        page: "portfolio",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "slussen_vatten",
	    headline: "Tekniska utmaningar i vattenomr&aring;det",
	    productioncompany: "Mediabolaget",
	    client: "Stockholms Stad",
	    techniques: "2D-animation",
		thumbnail: "images/content/small/slussen_vatten.jpg",
	    video: "https://www.youtube.com/embed/Z6BgjJ4cx28",
        image: "images/content/slussen_vatten.jpg",
		link: "NULL",
	    info: "Nya Slussen - tekniska utmaningar i vattenomr&aring;det",
	    content: "video",
	    status: "online",
        page: "portfolio",
		software: "NULL",
		tags: "NULL"

    }, 
    {   
        title: "slussen_berg",
	    headline: "Tekniska utmaningar i berg",
	    productioncompany: "Mediabolaget",
	    client: "Stockholms Stad",
	    techniques: "3D/2D-graphics, Animation, Rendering, Compositing",
		thumbnail: "images/content/small/slussen_berg.jpg",
	    video: "https://www.youtube.com/embed/EMtvIivVjSo",
        image: "images/content/slussen_berg.jpg",
		link: "NULL",
	    info: "Nya Slussen - tekniska utmaningar i berg",
	    content: "video",
	    status: "online",
        page: "portfolio",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "sbk",
	    headline: "Samr&aring;d",
	    productioncompany: "Mediabolaget",
	    client: "Stadsbyggnadskontoret",
	    techniques: "3D/2D-graphics, Animation, Rendering",
		thumbnail: "images/content/small/sbk.jpg",
	    video: "https://player.vimeo.com/video/76044004",
        image: "images/content/sbk.jpg",
		link: "NULL",
	    info: "Stadsbyggnadskontoret - Samr&aring;d",
	    content: "video",
	    status: "online",
        page: "portfolio",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "lagesrapport_2014",
	    headline: "l&auml;gesrapport v&aring;ren 2014",
	    productioncompany: "Mediabolaget",
	    client: "Stockholms Stad",
	    techniques: "3D/2D-graphics, Animation, Rendering",
		thumbnail: "images/content/small/lagesrapport_2014.jpg",
	    video: "https://www.youtube.com/embed/EpjR9HsBxIs",
        image: "images/content/lagesrapport_2014.jpg",
		link: "NULL",
	    info: "Slussen - l&auml;gesrapport v&aring;ren 2014",
	    content: "video",
	    status: "online",
        page: "portfolio",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "malibu_redesign",
	    headline: "Malibu - Redesign",
	    productioncompany: "Mediabolaget",
	    client: "Malibu",
	    techniques: "3D/2D-graphics, Animation, Rendering, Compositing",
		thumbnail: "images/content/small/malibu_redesign.jpg",
	    video: "https://player.vimeo.com/video/49221171",
        image: "images/content/malibu_redesign.jpg",
		link: "NULL",
	    info: "NULL",
	    content: "video",
	    status: "online",
        page: "portfolio",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "blc",
	    headline: "Bygglogistikcenter",
	    productioncompany: "Mediabolaget",
	    client: "Norra Djurg&aring;rdsstaden",
	    techniques: "3D/2D-graphics, Animation, Rendering, Compositing",
		thumbnail: "images/content/small/blc.jpg",
	    video: "https://www.youtube.com/embed/_Bu237Fl87k",
        image: "images/content/blc.jpg",
		link: "NULL",
	    info: "NULL",
	    content: "video",
	    status: "online",
        page: "portfolio",
		software: "NULL",
		tags: "NULL"

    },
    {
        title: "nds",
	    headline: "Norra Djurg&aring;rdsstaden",
	    productioncompany: "Mediabolaget",
	    client: "Norra Djurg&aring;rdsstaden",
	    techniques: "3D/2D-graphics, Animation, Rendering, Compositing",
		thumbnail: "images/content/small/nds.jpg",
	    video: "https://www.youtube.com/embed/Fqh8QRywnC4",
        image: "images/content/nds.jpg",
		link: "NULL",
	    info: "NULL",
	    content: "video",
	    status: "online",
        page: "portfolio",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "varberg",
	    headline: "Varberg utvecklas",
	    productioncompany: "Mediabolaget",
	    client: "Varbergs kommun",
	    techniques: "2D/Motion-graphics",
		thumbnail: "images/content/small/varberg.jpg",
	    video: "https://www.youtube.com/embed/GZJ2WsFmtdg",
        image: "images/content/varberg.jpg",
		link: "NULL",
	    info: "NULL",
	    content: "video",
	    status: "online",
        page: "portfolio",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "andfrankly",
	    headline: "&Frankly",
	    productioncompany: "Mediabolaget",
	    client: "&Frankly",
	    techniques: "2D-graphics, Animation, Rendering",
		thumbnail: "images/content/small/andfrankly.jpg",
	    video: "https://www.youtube.com/embed/pZgrz3Q274I",
        image: "images/content/andfrankly.jpg",
		link: "NULL",
	    info: "NULL",
	    content: "video",
	    status: "online",
        page: "portfolio",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "fi",
	    headline: "Så är det att jobba på Finansinspektionen",
	    productioncompany: "Mediabolaget",
	    client: "Finansinspektionen",
	    techniques: "3D/2D-graphics, Animation, Rendering",
		thumbnail: "images/content/small/fi.jpg",
	    video: "https://www.youtube.com/embed/GRatYup09I4",
        image: "images/content/fi.jpg",
		link: "NULL",
	    info: "NULL",
	    content: "video",
	    status: "online",
        page: "portfolio",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "katarinahissen",
	    headline: "Katarinahissen",
	    productioncompany: "Mediabolaget",
	    client: "Stockholms Stad",
	    techniques: "Hypertimelapse Photography, 2D-graphics, Animation",
		thumbnail: "images/content/small/katarinahissen.jpg",
	    video: "https://www.youtube.com/embed/gcqZvg6eisM",
        image: "images/content/katarinahissen.jpg",
		link: "NULL",
	    info: "NULL",
	    content: "video",
	    status: "online",
        page: "portfolio",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "FI_penning",
	    headline: "Penningtvätt",
	    productioncompany: "Mediabolaget",
	    client: "Finansinspektionen",
	    techniques: "2D-graphics, Animation, Rendering",
		thumbnail: "images/content/small/FI_penning.jpg",
	    video: "https://www.youtube.com/embed/-mIpOE8Eaf8",
        image: "images/content/FI_penning.jpg",
		link: "NULL",
	    info: "NULL",
	    content: "video",
	    status: "online",
        page: "portfolio",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "submarine",
	    headline: "Submarine",
	    productioncompany: "NULL",
	    client: "Personal Project",
	    techniques: "Cinema 4D and Arnold Renderer",
		thumbnail: "images/content/small/submarine.jpg",
	    video: "https://player.vimeo.com/video/328707422",
        image: "images/content/submarine.jpg",
		link: "NULL",
	    info: "Testing some stuff in Arnold renderer, modelling and shading...",
	    content: "video",
	    status: "online",
        page: "personal",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "slussen_nya_slussen_2019",
	    headline: "Vad ska vi bygga?",
	    productioncompany: "Mediabolaget",
	    client: "Stockholms Stad",
	    techniques: "3D/2D-graphics, Animation, Rendering, Compositing",
		thumbnail: "images/content/small/slussen_nya_slussen_2019.jpg",
	    video: "https://www.youtube.com/embed/RyiBQEs9Dfs",
        image: "images/content/slussen_nya_slussen_2019.jpg",
		link: "NULL",
	    info: "NULL",
	    content: "video",
	    status: "online",
        page: "portfolio",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "slussen_bron_del1",
	    headline: "Slussens nya huvudbron - Del 1",
	    productioncompany: "Mediabolaget",
	    client: "Stockholms Stad",
	    techniques: "3D/2D-graphics, Animation, Rendering, Compositing",
		thumbnail: "images/content/small/slussen_bron_del1.jpg",
	    video: "https://www.youtube.com/embed/I-SthvVZhxw",
        image: "images/content/slussen_bron_del1.jpg",
		link: "NULL",
	    info: "NULL",
	    content: "video",
	    status: "online",
        page: "portfolio",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "slussen_bron_del2",
	    headline: "Slussens nya huvudbron - Del 2",
	    productioncompany: "Mediabolaget",
	    client: "Stockholms Stad",
	    techniques: "3D/2D-graphics, Animation, Rendering, Compositing",
		thumbnail: "images/content/small/slussen_bron_del2.jpg",
	    video: "https://www.youtube.com/embed/v9se4vWMBJw",
        image: "images/content/slussen_bron_del2.jpg",
		link: "NULL",
	    info: "NULL",
	    content: "video",
	    status: "online",
        page: "portfolio",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "slussen_bussterminalen",
	    headline: "Nya Bussterminalen i Slussen",
	    productioncompany: "Mediabolaget",
	    client: "Stockholms Stad",
	    techniques: "3D/2D-graphics, Animation, Rendering, Compositing",
		thumbnail: "images/content/small/slussen_bussterminalen.jpg",
	    video: "https://www.youtube.com/embed/iqi75Muysnw",
        image: "images/content/slussen_bussterminalen.jpg",
		link: "NULL",
	    info: "NULL",
	    content: "video",
	    status: "online",
        page: "portfolio",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "mail_fast",
	    headline: "Mail Fast",
	    productioncompany: "NULL",
	    client: "Personal Project",
	    techniques: "Cinema 4D and Redshift Renderer",
		thumbnail: "images/content/small/mail_fast.jpg",
	    video: "https://player.vimeo.com/video/343598907",
        image: "images/content/mail_fast.jpg",
		link: "NULL",
	    info: "Testing some rigging, dynamics and rendering...",
	    content: "video",
	    status: "online",
        page: "personal",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "coffee",
	    headline: "Need Coffee?",
	    productioncompany: "NULL",
	    client: "Personal Project",
	    techniques: "Cinema 4D and Redshift Renderer",
		thumbnail: "images/content/small/coffee.jpg",
	    video: "https://player.vimeo.com/video/345004844",
        image: "images/content/coffee.jpg",
		link: "NULL",
	    info: "Character design and rigging test...",
	    content: "video",
	    status: "online",
        page: "personal",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "bulb",
	    headline: "Bulb Idea",
	    productioncompany: "NULL",
	    client: "Personal Project",
	    techniques: "Cinema 4D and Arnold Renderer",
		thumbnail: "images/content/small/bulb.jpg",
	    video: "https://player.vimeo.com/video/338879860",
        image: "images/content/bulb.jpg",
		link: "NULL",
	    info: "Having some fun with Arnold Renderer.",
	    content: "video",
	    status: "online",
        page: "personal",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "icecream",
	    headline: "Icecream",
	    productioncompany: "NULL",
	    client: "Personal Project",
	    techniques: "Cinema 4D and Redshift Renderer",
		thumbnail: "images/content/small/icecream.jpg",
	    video: "https://player.vimeo.com/video/349761203",
        image: "images/content/icecream.jpg",
		link: "NULL",
	    info: "Playing around with some character design and rigging...",
	    content: "video",
	    status: "online",
        page: "personal",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "nintendo",
	    headline: "Nintendo Medley",
	    productioncompany: "NULL",
	    client: "Personal Project",
	    techniques: "Cinema 4D and Redshift Renderer",
		thumbnail: "images/content/small/nintendo.jpg",
	    video: "https://player.vimeo.com/video/349960360",
        image: "images/content/nintendo.jpg",
		link: "https://vimeo.com/349960360",
	    info: "Testing some modelling techniques...",
	    content: "video",
	    status: "online",
        page: "personal",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "rbot",
	    headline: "R-Bot",
	    productioncompany: "NULL",
	    client: "Personal Project",
	    techniques: "Cinema 4D and Redshift Renderer",
		thumbnail: "images/content/small/rbot.jpg",
	    video: "https://player.vimeo.com/video/367203288",
        image: "images/content/rbot.jpg",
		link: "https://vimeo.com/367203288",
	    info: "Playing around with Redshift and Cinema 4D...",
	    content: "video",
	    status: "online",
        page: "personal",
		software: ["C4D", "Redshift", "AE"],
		tags: ["Animation", "3D"]

    }, 
    {
        title: "orc",
	    headline: "Redshift Orc",
	    productioncompany: "NULL",
	    client: "Personal Project",
	    techniques: "Cinema 4D and Redshift Renderer",
		thumbnail: "images/content/small/orc.jpg",
	    video: "https://player.vimeo.com/video/389546434",
        image: "images/content/orc.jpg",
		link: "https://vimeo.com/389546434",
	    info: "Playing around with Redshift, Cinema 4D and some non-destructive modelling and rigging...",
	    content: "video",
	    status: "online",
        page: "personal",
		software: ["C4D", "Redshift", "AE"],
		tags: ["Animation", "3D"]

    }, 
    {
        title: "hl_display",
	    headline: "Birth, life & death of a datastrip",
	    productioncompany: "Mediabolaget",
	    client: "HL Display",
	    techniques: "2D-graphics, Animation, Motion Design",
		thumbnail: "images/content/small/hl_display.jpg",
	    video: "",
        image: "images/content/hl_display.jpg",
		link: "NULL",
	    info: "NULL",
	    content: "video",
	    status: "offline",
        page: "portfolio",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "malibu_splash_2020",
	    headline: "Malibu Splash",
	    productioncompany: "Mediabolaget",
	    client: "Malibu",
	    techniques: "3D/2D-animation, Animation, Motion Design, Rendering",
		thumbnail: "images/content/small/malibu_splash_2020.jpg",
	    video: "https://player.vimeo.com/video/392795260",
        image: "images/content/malibu_splash_2020.jpg",
		link: "https://vimeo.com/392795260",
	    info: "NULL",
	    content: "video",
	    status: "online",
        page: "portfolio",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "ideal_nr1",
	    headline: "IDEaL!",
	    productioncompany: "Mediabolaget",
	    client: "Polisen",
	    techniques: "2D-graphics, Animation, Motion Design",
		thumbnail: "images/content/small/ideal_nr1.jpg",
	    video: "https://player.vimeo.com/video/392786690",
        image: "images/content/ideal_nr1.jpg",
		link: "https://vimeo.com/392786690",
	    info: "Film som gjordes för att förklara den svenska modellen IDEaL!",
	    content: "video",
	    status: "online",
        page: "portfolio",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "ideal_nr2",
	    headline: "IDEaL!",
	    productioncompany: "Mediabolaget",
	    client: "Polisen",
	    techniques: "2D-graphics, Animation, Motion Design",
		thumbnail: "images/content/small/ideal_nr2.jpg",
	    video: "",
        image: "images/content/ideal_nr2.jpg",
		link: "NULL",
	    info: "Film som gjordes för att förklara den svenska modellen IDEaL!",
	    content: "video",
	    status: "offline",
        page: "portfolio",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "hela_spektrat",
	    headline: "Hela Spektrat",
	    productioncompany: "Mediabolaget",
	    client: "Hela Spektrat",
	    techniques: "2D-animation, Motion Design",
		thumbnail: "images/content/small/hela_spektrat.jpg",
	    video: "https://player.vimeo.com/video/392785590",
        image: "images/content/hela_spektrat.jpg",
		link: "https://vimeo.com/392785590",
	    info: "Gjorde animationer till ett semenarium",
	    content: "video",
	    status: "online",
        page: "portfolio",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "3d_engine",
	    headline: "3D Engine",
	    productioncompany: "NULL",
	    client: "Personal Project",
	    techniques: "Javascript, html, css",
		thumbnail: "images/content/small/3d_engine.jpg",
	    video: "NULL",
        image: "images/content/3d_engine.jpg",
        link: "https://xpmoss.github.io/threedcube/",
	    info: "Testing coding with canvas. A 'fake' 3D box with javascript",
	    content: "html",
	    status: "online",
        page: "dev",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "snake",
	    headline: "Snake",
	    productioncompany: "NULL",
	    client: "School Project",
	    techniques: "C#",
		thumbnail: "images/content/small/snake.jpg",
	    video: "NULL",
        image: "images/content/snake.jpg",
		link: "https://github.com/xPMoss/snake",
	    info: "Snake Game made with C#<br>Link to Git: <a href='https://github.com/xPMoss/snake' target='_blank'>github.com/xPMoss/snake</a>",
	    content: "code",
	    status: "online",
        page: "dev",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "tw",
	    headline: "Tree view",
	    productioncompany: "NULL",
	    client: "Personal Project",
	    techniques: "Javascript, html, css",
		thumbnail: "images/content/small/tw.jpg",
	    video: "NULL",
		image: "images/content/small/tw.jpg",
        link: "https://xpmoss.github.io/treeview/",
	    info: "Coding with canvas. A W.I.P tree view with javascript",
	    content: "html",
	    status: "online",
        page: "dev",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "tmdb",
	    headline: "The Movie App",
	    productioncompany: "NULL",
	    client: "School Project",
	    techniques: "Javascript, html, css",
		thumbnail: "images/content/small/tmdb.jpg",
	    video: "",
		image: "images/content/small/tw.jpg",
        link: "https://xpmoss.github.io/tma/",
	    info: "Coding with Html, Css & Javascript. A movie website",
	    content: "html",
	    status: "online",
        page: "dev",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "ld",
	    headline: "Link Database",
	    productioncompany: "NULL",
	    client: "Personal Project",
	    techniques: "Javascript, html, css",
		thumbnail: "images/content/small/ld.jpg",
	    video: "",
		image: "images/content/small/tw.jpg",
        link: "https://xpmoss.github.io/ld/",
	    info: "Coding with Html, Css & Javascript. Testing some filtering code",
	    content: "html",
	    status: "online",
        page: "dev",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "linked",
	    headline: "LinkedIn Video",
	    productioncompany: "NULL",
	    client: "Personal Project",
	    techniques: "Cinema 4D and Redshift Renderer",
		thumbnail: "images/content/small/linked.jpg",
	    video: "https://player.vimeo.com/video/524351550",
		image: "NULL",
        link: "NULL",
	    info: "A animation I did for some self promotion",
	    content: "video",
	    status: "online",
        page: "personal",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "animlib",
	    headline: "Animation Library",
	    productioncompany: "NULL",
	    client: "Personal Project",
	    techniques: "Javascript",
		thumbnail: "images/content/small/animlib.jpg",
	    video: "NULL",
        image: "images/content/snake.jpg",
		link: "https://github.com/xPMoss/anim.lib",
	    info: "For easy animation directly in Html code.",
	    content: "code",
	    status: "online",
        page: "dev",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "calender",
	    headline: "Calender",
	    productioncompany: "NULL",
	    client: "Personal Project",
	    techniques: "Angular",
		thumbnail: "images/content/small/calender.jpg",
	    video: "NULL",
        image: "images/content/small/calender.jpg",
		link: "https://calender-angular-13656.web.app/",
	    info: "A calender for calculating worked hours",
	    content: "code",
	    status: "online",
        page: "dev",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "projects_collection",
	    headline: "Projects Collection",
	    productioncompany: "NULL",
	    client: "Personal Project",
	    techniques: "Angular",
		thumbnail: "images/content/medium/projects_collection.jpg",
	    video: "NULL",
        image: "images/content/medium/projects_collection.jpg",
		link: "https://projects-collection-3f14d.web.app/",
	    info: "A site for project collections",
	    content: "code",
	    status: "online",
        page: "dev",
		software: "NULL",
		tags: "NULL"

    }, 
    {
        title: "the_movie_app",
	    headline: "Movie App",
	    productioncompany: "NULL",
	    client: "Personal Project",
	    techniques: "Angular",
		thumbnail: "images/content/medium/tma.jpg",
	    video: "NULL",
        image: "images/content/medium/tma.jpg",
		link: "https://the-movie-app-344909.web.app/",
	    info: "A site for movie recommendations",
	    content: "code",
	    status: "online",
        page: "dev",
		software: "NULL",
		tags: "NULL"

    }
]

let linksData = [
    {
        logo:"LinkedIn", 
        text:"LinkedIn", 
        color:"0A66C2", 
        logoColor:"white", 
        classes:["me-2"],
        link:true,
        url:"https://www.linkedin.com/in/patrikmossbergg",
    },
    {
        logo:"GitHub", 
        text:"GitHub", 
        color:"000", 
        logoColor:"white", 
        classes:["me-2"],
        link:true,
        url:"https://github.com/xPMoss"
    },
    {
        logo:"turbosquid", 
        text:"turbosquid", 
        color:"FF8135", 
        logoColor:"white", 
        classes:["me-2"],
        link:true,
        url:"https://www.turbosquid.com/Search/Artists/wemg?referral=wemg"
    },
    {
        logo:"vimeo", 
        text:"vimeo", 
        color:"1AB7EA", 
        logoColor:"white", 
        classes:["me-2"],
        link:true,
        url:"https://vimeo.com/cgfx"
    },
    {
        logo:"behance", 
        text:"behance", 
        color:"1769FF", 
        logoColor:"white", 
        classes:["me-2"],
        link:true,
        url:"https://www.behance.net/xpm35"
    }
]

let badgeData_languages = [
    {
        logo:"Csharp", 
        text:"Csharp", 
        color:"512BD4", 
        logoColor:"white", 
        classes:["me-2"], 
        link:false, 
        url:"",
    },
    {logo:"typescript", text:"typescript", color:"3178C6", logoColor:"white", classes:["me-2"], link:false, url:""},
    {logo:"JavaScript", text:"JavaScript", color:"F7DF1E", logoColor:"black", classes:["me-2"], link:false, url:""},
    {logo:"html5", text:"html", color:"E34F26", logoColor:"white", classes:["me-2"], link:false, url:""},
    {logo:"css3", text:"css", color:"1572B6", logoColor:"white", classes:[], link:false, url:""}

]

//https://the-movie-service.web.app/
/*


    {
        title:"My webpage",
        image:"xpm.jpg",
        techniques:"Javascript, html, css",
        info:"My webpage",
        link:"https://xpm.one/"

    }




*/